sudo: required 
services: 
    - docker 

before_install:
    - docker build -t hemanth/docker-react -f Dockerfile.dev .

      
script:
    - docker run hemanth/docker-react npm run test -- -- coverage 
